# Generated by Django 4.2.7 on 2023-11-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
