# Generated by Django 4.2.7 on 2023-11-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productcomment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
